openapi: 3.0.0
info:
  version: 1.0.0
  title: OAuth2 provider Registration
  license:
    name: MIT
servers:
  - url: 'http://light-oauth2.swagger.io/v1'
paths:
  /provider:
    post:
      summary: 'Registe a new oauth provider '
      operationId: createProvider
      requestBody:
        description: todo object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Provider'
      tags:
        - providers
      security:
        - provider_auth:
            - 'read:provider'
            - write.provider
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'
        '201':
          description: Null response
    get:
      summary: 'Return list of registed oauth provider '
      operationId: getProviders
      tags:
        - providers
      security:
        - provider_auth:
            - 'read:provider'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Provider'
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/oauth2/provider/{providerId}':
    delete:
      summary: delete a provider by providerId
      operationId: deleteProviderById
      tags:
        - providers
      parameters:
        - name: providerId
          in: path
          required: true
          description: The id of the provider
          schema:
            type: string
      security:
        - provider_auth:
            - 'read:provider'
            - 'write:provider'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    provider_auth:
      type: oauth2
      description: This API uses OAuth 2 with the client credential grant flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://localhost:6882/token'
          scopes:
            'write:provider': modify provider
            'read:provider': read provider
  schemas:
    Provider:
      required:
        - serverUrl
      properties:
        providerId:
          type: string
        serverUrl:
          type: string
        uri:
          type: string
        providerName:
          type: integer
          format: int32
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
