openapi: 3.0.0

info:
  title: TestProject
  version: 1.0.0

servers:
  - url: 'https://localhost:8443/api'

paths:
  /testEndPoint:
    get:
      parameters:
        - $ref: '#/components/schemas/TestObject'
      responses:
        '200':
          description: History something something
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    TestObject:
      type: object
      properties:
        testProperty:
          type: string
